apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - echo "Hello, Kubernetes!" && sleep 5




