apiVersion: v1
kind: Pod
metadata:
  name: go-demo-app-multicontainer
  labels:
    app: go-demo-app
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: app
      image: ghcr.io/den-vasyliev/go-demo-app:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
    - name: log-sidecar
      image: busybox:1.36
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - tail -F /var/log/app/app.log
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app




