---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-volumes
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: app-pvc
      containers:
        - name: app
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/app/config
              readOnly: true
            - name: data-volume
              mountPath: /data
