apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-resources
  labels:
    app: go-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


