apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-liveness
  labels:
    app: go-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3




