apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: demo
  DB_PASSWORD: demo123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-secret-env
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret


