apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
  labels:
    app: go-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/den-vasyliev/go-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-app
  labels:
    app: go-demo-app
spec:
  selector:
    app: go-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP


